
package com.exlibris.dps;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CollectionWebServices", targetNamespace = "http://dps.exlibris.com/", wsdlLocation = "file:/C:/Users/u0077845/Documents/NetBeansProjects/RosettaCollection/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/libis-p-rosetta-1w.cc.kuleuven.be_1801/dpsws/repository/CollectionWebServices.wsdl")
public class CollectionWebServices_Service
    extends Service
{

    private final static URL COLLECTIONWEBSERVICES_WSDL_LOCATION;
    private final static WebServiceException COLLECTIONWEBSERVICES_EXCEPTION;
    private final static QName COLLECTIONWEBSERVICES_QNAME = new QName("http://dps.exlibris.com/", "CollectionWebServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/u0077845/Documents/NetBeansProjects/RosettaCollection/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/libis-p-rosetta-1w.cc.kuleuven.be_1801/dpsws/repository/CollectionWebServices.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COLLECTIONWEBSERVICES_WSDL_LOCATION = url;
        COLLECTIONWEBSERVICES_EXCEPTION = e;
    }

    public CollectionWebServices_Service() {
        super(__getWsdlLocation(), COLLECTIONWEBSERVICES_QNAME);
    }


    public CollectionWebServices_Service(URL wsdlLocation) {
        super(wsdlLocation, COLLECTIONWEBSERVICES_QNAME);
    }


    public CollectionWebServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }


    /**
     * 
     * @return
     *     returns CollectionWebServices
     */
    @WebEndpoint(name = "CollectionWebServicesPort")
    public CollectionWebServices getCollectionWebServicesPort() {
        return super.getPort(new QName("http://dps.exlibris.com/", "CollectionWebServicesPort"), CollectionWebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollectionWebServices
     */
    @WebEndpoint(name = "CollectionWebServicesPort")
    public CollectionWebServices getCollectionWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dps.exlibris.com/", "CollectionWebServicesPort"), CollectionWebServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COLLECTIONWEBSERVICES_EXCEPTION!= null) {
            throw COLLECTIONWEBSERVICES_EXCEPTION;
        }
        return COLLECTIONWEBSERVICES_WSDL_LOCATION;
    }

}
