
package com.exlibris.dps;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IEWebServices", targetNamespace = "http://dps.exlibris.com/", wsdlLocation = "http://libis-p-rosetta-1w.cc.kuleuven.be:1801/dpsws/repository/IEWebServices?wsdl")
public class IEWebServices_Service
    extends Service
{

    private final static URL IEWEBSERVICES_WSDL_LOCATION;
    private final static WebServiceException IEWEBSERVICES_EXCEPTION;
    private final static QName IEWEBSERVICES_QNAME = new QName("http://dps.exlibris.com/", "IEWebServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://libis-p-rosetta-1w.cc.kuleuven.be:1801/dpsws/repository/IEWebServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IEWEBSERVICES_WSDL_LOCATION = url;
        IEWEBSERVICES_EXCEPTION = e;
    }

    public IEWebServices_Service() {
        super(__getWsdlLocation(), IEWEBSERVICES_QNAME);
    }

    public IEWebServices_Service(URL wsdlLocation) {
        super(wsdlLocation, IEWEBSERVICES_QNAME);
    }

    public IEWebServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IEWebServices
     */
    @WebEndpoint(name = "IEWebServicesPort")
    public IEWebServices getIEWebServicesPort() {
        return super.getPort(new QName("http://dps.exlibris.com/", "IEWebServicesPort"), IEWebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEWebServices
     */
    @WebEndpoint(name = "IEWebServicesPort")
    public IEWebServices getIEWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dps.exlibris.com/", "IEWebServicesPort"), IEWebServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IEWEBSERVICES_EXCEPTION!= null) {
            throw IEWEBSERVICES_EXCEPTION;
        }
        return IEWEBSERVICES_WSDL_LOCATION;
    }

}
