
package com.exlibris.dps;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidCollectionInfoException", targetNamespace = "http://dps.exlibris.com/")
public class InvalidCollectionInfoException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidCollectionInfoException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidCollectionInfoException_Exception(String message, InvalidCollectionInfoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidCollectionInfoException_Exception(String message, InvalidCollectionInfoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.exlibris.dps.InvalidCollectionInfoException
     */
    public InvalidCollectionInfoException getFaultInfo() {
        return faultInfo;
    }

}
