
package com.exlibris.dps;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoCollectionFoundException", targetNamespace = "http://dps.exlibris.com/")
public class NoCollectionFoundException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoCollectionFoundException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NoCollectionFoundException_Exception(String message, NoCollectionFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NoCollectionFoundException_Exception(String message, NoCollectionFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.exlibris.dps.NoCollectionFoundException
     */
    public NoCollectionFoundException getFaultInfo() {
        return faultInfo;
    }

}
